// changes-29 B4 — the takeaways block, and the property it exists to prove.
//
// **It renders identically whether an editor typed the list or AI filled it.**
// There is no AI-shaped variant, no badge and no prop that says where the words
// came from — which is what makes ADR-097's "every field AI fills is a field a
// human can fill" a structural fact rather than a promise. If a later PR adds
// a "generated by AI" flourish, the first assertion below is what stops it.
// Plain DOM assertions, not jest-dom: this package loads no matcher setup
// file, and every other component test here reads the DOM directly.
import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";

import { KeyTakeaways } from "./key-takeaways.tsx";

const HUMAN = ["Spreads widen at the open.", "A pip is not a point.", "Leverage cuts both ways."];

afterEach(cleanup);

describe("KeyTakeaways", () => {
  it("renders the same markup for a hand-typed and a generated list", () => {
    const { container: typed } = render(<KeyTakeaways heading="Key takeaways" items={HUMAN} />);
    const typedHtml = typed.innerHTML;

    // The identical array, "generated" — the component is not told, and cannot
    // be told, which is the point.
    const { container: generated } = render(
      <KeyTakeaways heading="Key takeaways" items={[...HUMAN]} />,
    );
    expect(generated.innerHTML).toBe(typedHtml);
  });

  it("renders NOTHING when the list is empty", () => {
    // An empty card with a heading is a promise the page did not keep.
    const { container } = render(<KeyTakeaways heading="Key takeaways" items={[]} />);
    expect(container.innerHTML).toBe("");
  });

  it("renders nothing when every entry is blank", () => {
    const { container } = render(<KeyTakeaways heading="Key takeaways" items={["", "   "]} />);
    expect(container.innerHTML).toBe("");
  });

  it("drops a blank entry without dropping the block", () => {
    render(<KeyTakeaways heading="Key takeaways" items={["Kept.", "  "]} />);
    expect(screen.getAllByRole("listitem")).toHaveLength(1);
  });

  it("is a real list, so a screen reader can count it", () => {
    // The count is half the value of a takeaways block.
    render(<KeyTakeaways heading="Key takeaways" items={HUMAN} />);
    expect(screen.getByRole("list")).not.toBeNull();
    expect(screen.getAllByRole("listitem")).toHaveLength(3);
  });

  it("renders its heading as a heading, not as bold text", () => {
    render(<KeyTakeaways heading="Key takeaways" items={HUMAN} />);
    expect(screen.getByRole("heading", { name: "Key takeaways" })).not.toBeNull();
  });

  it("renders a hostile entry as TEXT", () => {
    // §12 #5: a `<script>` in a suggestion arrives as visible characters. The
    // block takes strings and React escapes them; there is no HTML path here
    // at all, and `ai-output.test.ts` guards the absence.
    const hostile = '<script>alert("x")</script>';
    render(<KeyTakeaways heading="Key takeaways" items={[hostile, "b", "c"]} />);
    expect(screen.getByText(hostile)).not.toBeNull();
    expect(document.querySelector("script")).toBeNull();
  });
});
