// Correlation and the risk meter against real MariaDB (ADR-088).
//
// Two properties carry the whole file, and both are about HONESTY rather than
// about arithmetic — the arithmetic is already property-tested in
// `@repo/utils`:
//
//   1. a sample below the window renders "—", never a number;
//   2. a component that cannot report is EXCLUDED and COUNTED, never
//      zero-filled.
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { MariaDbContainer, type StartedMariaDbContainer } from "@testcontainers/mariadb";
import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";

import type * as AnalyticsModule from "./market-analytics.ts";
import type { db as DbClient } from "@repo/db";

const dbPackageRoot = fileURLToPath(new URL("../../db", import.meta.url));
const prismaCli = createRequire(import.meta.url).resolve("prisma/build/index.js");

let container: StartedMariaDbContainer;
let db: typeof DbClient;
let analytics: typeof AnalyticsModule;

beforeAll(async () => {
  container = await new MariaDbContainer("mariadb:11.4")
    .withDatabase("mbfx_test")
    .withUsername("test")
    .withUserPassword("test")
    .start();

  const url = container.getConnectionUri().replace(/^mariadb:/, "mysql:");
  execFileSync(process.execPath, [prismaCli, "migrate", "deploy"], {
    cwd: dbPackageRoot,
    env: { ...process.env, DATABASE_URL: url },
    stdio: "pipe",
  });

  process.env.DATABASE_URL = url;
  db = (await import("@repo/db")).db;
  analytics = await import("./market-analytics.ts");
}, 180_000);

afterAll(async () => {
  await db.$disconnect();
  await container.stop();
});

afterEach(async () => {
  await db.marketDailyBar.deleteMany();
  await db.marketInstrument.deleteMany();
});

/** An instrument with `days` closes generated by `shape`. */
async function makeSeries(symbol: string, days: number, shape: (i: number) => number) {
  const instrument = await db.marketInstrument.create({
    data: { symbol, displayName: symbol, kind: "PAIR", base: symbol.split("/")[0], quote: "USD" },
  });
  if (days > 0) {
    await db.marketDailyBar.createMany({
      data: Array.from({ length: days }, (_, i) => {
        const close = shape(i);
        return {
          instrumentId: instrument.id,
          date: new Date(Date.UTC(2026, 0, 1 + i)),
          open: close,
          high: close * 1.01,
          low: close * 0.99,
          close,
        };
      }),
    });
  }
  return instrument;
}

describe("getCorrelationMatrix", () => {
  it("finds two series with identical returns perfectly correlated", async () => {
    const a = await makeSeries("AAA/USD", 40, (i) => 100 * (1 + Math.sin(i / 4) / 50));
    const b = await makeSeries("BBB/USD", 40, (i) => 50 * (1 + Math.sin(i / 4) / 50));

    const view = await analytics.getCorrelationMatrix("30d", [a.id, b.id]);
    expect(view.matrix[a.id]![b.id]!).toBeCloseTo(1, 6);
    expect(view.matrix[a.id]![a.id]).toBe(1);
  });

  it("finds a return-mirrored series perfectly inversely correlated", async () => {
    const a = await makeSeries("AAA/USD", 40, (i) => 100 * (1 + Math.sin(i / 4) / 50));
    const b = await makeSeries("BBB/USD", 40, (i) => 100 * (1 - Math.sin(i / 4) / 50));

    const view = await analytics.getCorrelationMatrix("30d", [a.id, b.id]);
    expect(view.matrix[a.id]![b.id]!).toBeLessThan(-0.9);
  });

  it('renders "—" for a series below the window, and NAMES it', async () => {
    // ADR-088 #3. An instrument that vanishes from the grid is a question a
    // reader cannot answer; one that is named is.
    const a = await makeSeries("AAA/USD", 40, (i) => 100 + i);
    const short = await makeSeries("SSS/USD", 4, (i) => 100 + i);

    const view = await analytics.getCorrelationMatrix("30d", [a.id, short.id]);
    expect(view.matrix[short.id]![short.id]).toBeNull();
    expect(view.matrix[a.id]![short.id]).toBeNull();
    expect(view.instruments.map((i) => i.symbol)).toEqual(["AAA/USD"]);
    expect(view.excluded.map((i) => i.symbol)).toEqual(["SSS/USD"]);
  });

  it("reads only the instruments the tool configured", async () => {
    // An empty list renders an empty state rather than silently falling back
    // to every instrument — a matrix nobody asked for is worse than a message.
    await makeSeries("AAA/USD", 40, (i) => 100 + i);
    const view = await analytics.getCorrelationMatrix("30d", []);
    expect(view.instruments).toEqual([]);
    expect(view.asOf).toBeNull();
  });

  it("skips an inactive instrument", async () => {
    const a = await makeSeries("AAA/USD", 40, (i) => 100 + i);
    const b = await makeSeries("BBB/USD", 40, (i) => 100 + i);
    await db.marketInstrument.update({ where: { id: b.id }, data: { isActive: false } });

    const view = await analytics.getCorrelationMatrix("30d", [a.id, b.id]);
    expect(view.instruments).toHaveLength(1);
  });

  it("reports the newest bar as its as-of", async () => {
    const a = await makeSeries("AAA/USD", 40, (i) => 100 + i);
    const view = await analytics.getCorrelationMatrix("30d", [a.id]);
    expect(view.asOf).toBe(new Date(Date.UTC(2026, 0, 40)).toISOString());
  });
});

describe("getCorrelationMatrices", () => {
  it("computes every offered window from ONE read", async () => {
    const a = await makeSeries("AAA/USD", 120, (i) => 100 * (1 + Math.sin(i / 5) / 50));
    const b = await makeSeries("BBB/USD", 120, (i) => 100 * (1 + Math.cos(i / 5) / 50));

    const all = await analytics.getCorrelationMatrices(["5d", "30d", "90d"], [a.id, b.id]);
    expect(Object.keys(all).sort()).toEqual(["30d", "5d", "90d"]);
    for (const window of ["5d", "30d", "90d"]) {
      expect(all[window]!.instruments).toHaveLength(2);
    }
  });

  it("gives DIFFERENT windows different answers", async () => {
    // The trap this catches: handing every window the whole history would
    // make a 5d window quietly read 120 days of it, and all seven would agree.
    const a = await makeSeries("AAA/USD", 120, (i) => 100 * (1 + Math.sin(i / 3) / 40));
    const b = await makeSeries("BBB/USD", 120, (i) => 100 * (1 + Math.sin(i / 11) / 40));

    const all = await analytics.getCorrelationMatrices(["5d", "90d"], [a.id, b.id]);
    const short = all["5d"]!.matrix[a.id]![b.id]!;
    const long = all["90d"]!.matrix[a.id]![b.id]!;
    expect(short).not.toBeCloseTo(long, 3);
  });

  it("excludes a series per window — short history fails the long one only", async () => {
    const a = await makeSeries("AAA/USD", 120, (i) => 100 * (1 + Math.sin(i / 5) / 50));
    const medium = await makeSeries("MMM/USD", 20, (i) => 100 * (1 + Math.cos(i / 5) / 50));

    const all = await analytics.getCorrelationMatrices(["5d", "90d"], [a.id, medium.id]);
    expect(all["5d"]!.instruments.map((i) => i.symbol).sort()).toEqual(["AAA/USD", "MMM/USD"]);
    expect(all["90d"]!.excluded.map((i) => i.symbol)).toEqual(["MMM/USD"]);
  });
});

describe("getRiskSentiment", () => {
  const bands = { riskOffBelow: 35, riskOnAbove: 65 };

  it("scores a basket and bands it", async () => {
    const rising = await makeSeries("SPX/USD", 100, (i) => 100 + i * 0.1 + (i === 99 ? 20 : 0));
    const view = await analytics.getRiskSentiment(
      [{ instrumentId: rising.id, weight: 1, direction: "risk-on" }],
      { lookbackDays: 60, ...bands },
    );
    expect(view.score).not.toBeNull();
    expect(view.band).toBe("risk-on");
    expect(view.reporting).toMatchObject({ reported: 1, total: 1 });
  });

  it("EXCLUDES a silent component and NAMES it by symbol", async () => {
    // ADR-088 #5, and the reason the name matters: "we could not read
    // XAU/USD" is a sentence a reader can act on; a cuid is not.
    const good = await makeSeries("SPX/USD", 100, (i) => 100 + i * 0.1 + (i === 99 ? 20 : 0));
    const silent = await makeSeries("XAU/USD", 2, () => 2400);

    const view = await analytics.getRiskSentiment(
      [
        { instrumentId: good.id, weight: 1, direction: "risk-on" },
        { instrumentId: silent.id, weight: 1, direction: "risk-off" },
      ],
      { lookbackDays: 60, ...bands },
    );
    expect(view.reporting.reported).toBe(1);
    expect(view.reporting.total).toBe(2);
    expect(view.reporting.excluded).toEqual(["XAU/USD"]);
    // Not zero-filled: the silent one contributes NOTHING, rather than a 0
    // that would drag the score toward risk-off.
    expect(view.components.map((c) => c.symbol)).toEqual(["SPX/USD"]);
  });

  it("returns a null score when NOTHING in the basket can report", async () => {
    const silent = await makeSeries("XAU/USD", 2, () => 2400);
    const view = await analytics.getRiskSentiment(
      [{ instrumentId: silent.id, weight: 1, direction: "risk-off" }],
      { lookbackDays: 60, ...bands },
    );
    expect(view.score).toBeNull();
    expect(view.band).toBeNull();
    expect(view.history).toEqual([]);
  });

  it("returns a null score for an empty basket rather than throwing", async () => {
    const view = await analytics.getRiskSentiment([], { lookbackDays: 60, ...bands });
    expect(view.score).toBeNull();
    expect(view.reporting.total).toBe(0);
  });

  it("flips a risk-off component: gold surging is risk coming OFF", async () => {
    const surging = await makeSeries("XAU/USD", 100, (i) => 2400 + (i === 99 ? 300 : i * 0.1));
    const view = await analytics.getRiskSentiment(
      [{ instrumentId: surging.id, weight: 1, direction: "risk-off" }],
      { lookbackDays: 60, ...bands },
    );
    expect(view.band).toBe("risk-off");
  });

  it("builds a history the sparkline can draw, oldest first", async () => {
    const series = await makeSeries("SPX/USD", 160, (i) => 100 * (1 + Math.sin(i / 7) / 30));
    const view = await analytics.getRiskSentiment(
      [{ instrumentId: series.id, weight: 1, direction: "risk-on" }],
      { lookbackDays: 60, ...bands },
    );
    expect(view.history.length).toBeGreaterThan(30);
    const dates = view.history.map((p) => p.date);
    expect([...dates].sort()).toEqual(dates);
    for (const point of view.history) {
      expect(point.score).toBeGreaterThanOrEqual(0);
      expect(point.score).toBeLessThanOrEqual(100);
    }
  });

  it("OMITS a history point it could not compute rather than plotting zero", async () => {
    // A sparkline dipping to zero reads as a crash. Silence reads as silence.
    // 62 closes against a 60-day lookback: at the OLDEST history points the
    // slice leaves two or three closes, which is one return — below what a
    // percentile rank needs, so those points cannot be computed at all.
    const shortish = await makeSeries("SPX/USD", 62, (i) => 100 * (1 + Math.sin(i / 7) / 30));
    const view = await analytics.getRiskSentiment(
      [{ instrumentId: shortish.id, weight: 1, direction: "risk-on" }],
      { lookbackDays: 60, ...bands },
    );
    // Fewer than the 60 points asked for: the ones that could not be computed
    // are missing from the series rather than present at zero.
    expect(view.history.length).toBeLessThan(60);
    expect(view.history.length).toBeGreaterThan(0);

    // NOT `every(p => p.score > 0)`: a score of exactly 0 is a legitimate
    // reading — it means the latest move was the lowest in its own history,
    // which is maximally risk-off. The property that matters is that every
    // point carries a REAL date from a bar, because a zero-filled point would
    // have to invent one.
    const dates = new Set(view.history.map((p) => p.date));
    expect(dates.size).toBe(view.history.length);
    for (const point of view.history) {
      expect(point.date).toMatch(/^2026-\d{2}-\d{2}$/);
      expect(Number.isFinite(point.score)).toBe(true);
    }
  });

  it("carries the bands and lookback through, so the widget draws the right scale", async () => {
    const series = await makeSeries("SPX/USD", 100, (i) => 100 + i);
    const view = await analytics.getRiskSentiment(
      [{ instrumentId: series.id, weight: 1, direction: "risk-on" }],
      { lookbackDays: 45, riskOffBelow: 20, riskOnAbove: 80 },
    );
    expect(view.lookbackDays).toBe(45);
    expect(view.bands).toEqual({ riskOffBelow: 20, riskOnAbove: 80 });
  });
});
