-- AlterTable
ALTER TABLE `content_references` MODIFY `sourceType` ENUM('PAGE_VERSION', 'MENU_ITEM', 'CARD_TEMPLATE', 'STYLE_PRESET', 'LAYOUT_TEMPLATE', 'ARTICLE', 'COURSE', 'BRAND', 'SETTING', 'VIDEO_TOPIC', 'QUIZ') NOT NULL;

-- AlterTable
ALTER TABLE `quizzes` ADD COLUMN `coverAssetId` VARCHAR(191) NULL;
