-- AlterTable
ALTER TABLE `article_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `course_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `email_template_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `glossary_term_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `lesson_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `page_translations` MODIFY `status` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `quiz_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `tool_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `video_topic_translations` MODIFY `translationStatus` ENUM('DRAFT', 'TRANSLATED', 'NEEDS_REVIEW', 'OUTDATED', 'MACHINE_TRANSLATED') NOT NULL DEFAULT 'DRAFT';
