import { expect, test } from "@playwright/test";
import { seededArticle } from "../db.ts";
import { expectNoSeriousAxeViolations } from "../axe.ts";

// changes-07 plan criterion 19, as an anonymous visitor.
//
// The anonymous /admin check below is the WEAK half of ADR-006's cross-surface
// gate and stays here because it is cheap: an anonymous request has no session
// cookie and dies at `proxy.ts`. The half that matters — a real LEARNER
// session, refused for `userType` alone by the layout and the services behind
// it — is `learner-admin-probe.spec.ts`.

test("emits both the article and FAQPage JSON-LD graphs", async ({ page }) => {
  const article = seededArticle();
  await page.goto(`/news/${article.slug}`);

  const graphs = await page.locator('script[type="application/ld+json"]').allTextContents();
  const parsed = graphs.map((g) => JSON.parse(g) as { "@type": string; mainEntity?: unknown[] });
  const types = parsed.map((g) => g["@type"]);

  expect(types).toContain("AnalysisNewsArticle");
  expect(types).toContain("FAQPage");

  // The FAQPage mirrors the stored rows — the whole admin → DB → public path.
  const faq = parsed.find((g) => g["@type"] === "FAQPage");
  const questions = (faq?.mainEntity as { name: string }[]).map((q) => q.name);
  expect(questions).toEqual(article.faqItems.map((f) => f.question));
});

test("renders the FAQ accordion and the article body", async ({ page }) => {
  const article = seededArticle();
  await page.goto(`/news/${article.slug}`);

  await expect(page.getByRole("heading", { name: "Frequently asked questions" })).toBeVisible();
  for (const item of article.faqItems) {
    await expect(page.getByText(item.question, { exact: true })).toBeVisible();
  }
});

test("omits the robots meta when indexing and following are both allowed", async ({ page }) => {
  const article = seededArticle();
  await page.goto(`/news/${article.slug}`);

  // noIndex and noFollow are independent since changes-07; with both allowed
  // the tag should be absent entirely rather than emitted as "index, follow".
  expect(article.noIndex).toBe(false);
  expect(article.noFollow).toBe(false);
  await expect(page.locator('meta[name="robots"]')).toHaveCount(0);
  await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
    "content",
    /summary(_large_image)?/,
  );
});

test("renders the key takeaways block, and it passes axe", async ({ page }) => {
  // changes-29 B4's one public surface, and the only AI-adjacent thing a
  // VISITOR ever sees. Its a11y was owed to Module 14 and could not be checked
  // before: the block renders only for a non-empty list, and no article the
  // suite loaded had one until `e2e-fixtures.ts` gave the sample article three.
  const article = seededArticle();
  await page.goto(`/news/${article.slug}`);

  const takeaways = page.getByRole("heading", { name: "Key takeaways" });
  await expect(takeaways).toBeVisible();

  // A LIST, not three paragraphs — the shape is what makes it skimmable with a
  // screen reader, which is the whole reason the block exists.
  await expect(page.getByRole("listitem").filter({ hasText: "1-2% of your account" })).toHaveCount(
    1,
  );

  // ADR-097 #4's consequence, asserted where a reader would see it: nothing on
  // the page says who wrote these words. A "generated by AI" badge would make
  // the column a provenance record, which it deliberately is not.
  const main = await page.locator("main").innerText();
  expect(main).not.toMatch(/generated by AI|AI-generated|machine.generated/i);

  await expectNoSeriousAxeViolations(page);
});

test("ADR-006 — an anonymous visitor cannot reach any /admin route", async ({ page }) => {
  for (const path of ["/admin", "/admin/articles", "/admin/users", "/admin/settings"]) {
    const response = await page.goto(path);
    // Either bounced to sign-in by the proxy, or refused outright. What must
    // never happen is a 200 that renders admin content.
    const url = page.url();
    const redirectedToSignIn = url.includes("/sign-in");
    const refused = (response?.status() ?? 200) >= 400;
    expect(redirectedToSignIn || refused, `${path} was reachable anonymously`).toBe(true);
  }
});
