// apps/web/app/[locale]/layout.tsx
//
// The one place where theme, locale, direction, and dark mode meet.
// Everything is resolved server-side so the first paint is already branded
// and already in the right language — no flash, no layout shift.

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "next-themes";

import { getActiveTheme, buildThemeStyleSheet } from "@repo/theme";
import { getActiveLocales, getMessages } from "@repo/i18n/server";
import { getPublicSettings } from "@repo/settings/server";
import { Toaster } from "@repo/ui/sonner";

import "./globals.css";

export async function generateStaticParams() {
  const locales = await getActiveLocales();
  return locales.map((l) => ({ locale: l.code }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const settings = await getPublicSettings("general");
  const seo = await getPublicSettings("seo");

  return {
    // "%s | Learn Forex" — template is admin-editable, not hardcoded.
    title: {
      default: settings["site.name"] ?? "Forex Learning Portal",
      template: seo["seo.titleTemplate"] ?? "%s | Forex Learning Portal",
    },
    description: settings["site.description"],
    icons: { icon: settings["site.faviconUrl"] ?? "/favicon.ico" },
    openGraph: {
      siteName: settings["site.name"],
      locale,
      type: "website",
    },
  };
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  const locales = await getActiveLocales();
  const active = locales.find((l) => l.code === locale);
  if (!active) notFound();

  // Parallel — none of these depend on each other.
  const [theme, messages, settings] = await Promise.all([
    getActiveTheme("web"),
    getMessages(locale),
    getPublicSettings("general"),
  ]);

  return (
    <html
      lang={locale}
      dir={active.direction.toLowerCase()}
      suppressHydrationWarning // next-themes writes the class before hydration
    >
      <head>
        {/*
          Injected ahead of the app CSS so component styles can override,
          and ahead of paint so the brand is correct on the first frame.
          Content comes from our own database and is generated by
          buildThemeStyleSheet — never from user input.
        */}
        <style
          id="brand-tokens"
          dangerouslySetInnerHTML={{ __html: buildThemeStyleSheet(theme) }}
        />
      </head>
      <body className="min-h-screen bg-background font-sans text-foreground antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme={settings["site.defaultThemeMode"] ?? "system"}
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
            <Toaster position="top-right" />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
